# DB에서 데이터를 받아온 후 null값 처리
## from sklearn.impute import SimpleImputer 사용

In [1]:
!cd

C:\Users\j\K-Digital_multi\KDstudy\실습\Sql_Data understanding


In [2]:
import pymysql.cursors
import pandas as pd

In [28]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost', user='me', 
                       password='1234', db='tip', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "select * from tips;"
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
    
#       df.to_csv('query.csv')

finally:

   conn.close()

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner   2.0
1         10.34  1.66    Male     No  Sun  Dinner   3.0
2         21.01  3.50    Male     No  Sun  Dinner   3.0
3         23.68  3.31    Male     No  Sun  Dinner   2.0
4         24.59  3.61  Female     No  Sun  Dinner   4.0
..          ...   ...     ...    ...  ...     ...   ...
244       16.99  1.01  Female     No  Sun  Dinner   2.0
245       10.34  1.66    None     No  Sun  Dinner   3.0
246       10.34  1.66    None     No  Sun  Dinner   3.0
247       10.34  1.66    Male     No  Sun    None   3.0
248       10.34  1.66    Male     No  Sun  Dinner   NaN

[249 rows x 7 columns]


In [29]:
df["sex"] = df["sex"].replace({"Female" : 0, "Male" : 1})
# tips['sex'].replace(~~~~, inplace = True) 해당 변경값을 바로 변수에 투입
# 
df["smoker"] = df["smoker"].replace({"No" : 0, "Yes" : 1})
df["day"] = df["day"].replace({"Thur" : 0, "Fri" : 1, "Sat" : 2, "Sun" : 3})
df["time"] = df["time"].replace({"Lunch" : 0, "Dinner" : 1})


In [ ]:
# 열 삭제 
# df = df.drop('day',axis = 1)

In [ ]:
# df.replace('',np.nan,inplace=True) 
# null 값으로 바꿔줌

In [30]:
df.isnull().sum()

total_bill    0
tip           0
sex           2
smoker        0
day           0
time          1
size          1
dtype: int64

In [6]:
df['smoker'].unique()

array([0, 1], dtype=int64)

In [31]:
from numpy import isnan
from sklearn.impute import SimpleImputer

In [32]:
data = df.values # array값으로 바꿔줌

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  249 non-null    float64
 1   tip         249 non-null    float64
 2   sex         247 non-null    float64
 3   smoker      249 non-null    int64  
 4   day         249 non-null    int64  
 5   time        248 non-null    float64
 6   size        248 non-null    float64
dtypes: float64(5), int64(2)
memory usage: 13.7 KB


In [35]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  249.000000  249.000000  247.000000  249.000000  249.000000  248.000000   
mean    19.622972    2.968795    0.643725    0.373494    1.751004    0.725806   
std      8.893766    1.385573    0.479870    0.484706    1.158006    0.447009   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.160000    2.000000    0.000000    0.000000    1.000000    0.000000   
50%     17.510000    2.750000    1.000000    0.000000    2.000000    1.000000   
75%     24.060000    3.510000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size  
count  248.000000  
mean     2.572581  
std      0.945249  
min      1.000000  
25%      2.000000  
50%      2.000000  
75%      3.000000  
max      6.000000

In [33]:
data.shape

(249, 7)

In [36]:
data[:,6]

array([ 2.,  3.,  3.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  4.,  2.,
        4.,  2.,  2.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  4.,  2.,  4.,
        2.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,  3.,  3.,  3.,  3.,
        3.,  3.,  2.,  2.,  2.,  4.,  2.,  2.,  4.,  3.,  2.,  2.,  2.,
        4.,  2.,  4.,  2.,  4.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  4.,
        2.,  2.,  2.,  2.,  1.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  3.,  2.,  3.,  2.,  4.,
        2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  6.,  2.,  2.,  2.,  3.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  5.,
        6.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  4.,  4.,  5.,
        6.,  4.,  2.,  4.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  4.,  2.,
        2.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  4

In [37]:
sum(isnan(data).flatten())

4

In [38]:
imputer = SimpleImputer(strategy = 'median')

In [39]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [40]:
data_trans = imputer.transform(data)

In [41]:
data_trans[:,6]

array([2., 3., 3., 2., 4., 4., 2., 4., 2., 2., 2., 4., 2., 4., 2., 2., 3.,
       3., 3., 3., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 4., 2., 4.,
       2., 3., 3., 3., 3., 3., 3., 2., 2., 2., 4., 2., 2., 4., 3., 2., 2.,
       2., 4., 2., 4., 2., 4., 2., 2., 4., 2., 2., 2., 4., 3., 3., 2., 1.,
       2., 2., 2., 3., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 1., 2., 2.,
       4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 1., 3., 2., 3., 2., 4., 2., 2.,
       4., 2., 2., 2., 2., 2., 6., 2., 2., 2., 3., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 6., 5., 6., 2., 2., 3., 2., 2., 2., 2., 2., 3.,
       4., 4., 5., 6., 4., 2., 4., 4., 2., 3., 2., 2., 3., 2., 4., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 3., 4., 2., 5., 3.,
       5., 3., 3., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 3., 2., 2., 2.,
       4., 3., 3., 4., 2., 2., 3., 4., 4., 2., 3., 2., 5., 2., 2., 4., 2.,
       2., 1., 3., 2., 2.

In [42]:
df_trans = pd.DataFrame(data_trans)

In [43]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [44]:
df_trans

0     1    2    3    4    5    6
0    16.99  1.01  0.0  0.0  3.0  1.0  2.0
1    10.34  1.66  1.0  0.0  3.0  1.0  3.0
2    21.01  3.50  1.0  0.0  3.0  1.0  3.0
3    23.68  3.31  1.0  0.0  3.0  1.0  2.0
4    24.59  3.61  0.0  0.0  3.0  1.0  4.0
..     ...   ...  ...  ...  ...  ...  ...
244  16.99  1.01  0.0  0.0  3.0  1.0  2.0
245  10.34  1.66  1.0  0.0  3.0  1.0  3.0
246  10.34  1.66  1.0  0.0  3.0  1.0  3.0
247  10.34  1.66  1.0  0.0  3.0  1.0  3.0
248  10.34  1.66  1.0  0.0  3.0  1.0  2.0

[249 rows x 7 columns]